/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dashboard;

import DAO.ConnectionFactory;
import DAO.ListaGenerosDAO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import loginCadastro.UsuarioLogado;

/**
 *
 * @author Ana Komase
 */
public class TelaGeneroFav extends javax.swing.JFrame {


    private List<Integer> idsGenerosFavoritos = new ArrayList<Integer>();
    private List<Integer> idsGeneroNaoFavorito = new ArrayList<Integer>();
    /**
     * Creates new form TelaGeneroFav
     */
    public TelaGeneroFav() {
        initComponents();
        preencherTabela();
        preencherComboBoxDeFavoritos();
        preencherComboBoxNaoFavoritos();
        setLocationRelativeTo(null);

    }

    private void preencherTabela() {
        try {
            List<GeneroFavorito> generos = DAO.ListaGenerosDAO.obterGenerosFavoritos();
            DefaultTableModel model;
            model = new DefaultTableModel(new Object[]{"Genero", "Data de Inserção"}, 0);
            //0 é o número de linhas vazias que seriam adicionadas na tabela a partir de
            //uma nova construção da tabela, feita através do new DTM.
            for (GeneroFavorito f : generos) {
                model.addRow(new Object[]{f.getTipo(), f.getRegistro()});
            }
            tbGeneroFavorito.setModel(model);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Tente novamente");
        }
    }

    private void preencherComboBoxDeFavoritos() {
        deleteCombo.removeAllItems();
        idsGenerosFavoritos = new ArrayList();
        try {
            List<GeneroFavorito> generos = DAO.ListaGenerosDAO.obterGenerosFavoritos();

            for (GeneroFavorito f : generos) {
                deleteCombo.addItem(f.getTipo());
                idsGenerosFavoritos.add(f.getIdGeneroFavorito());

            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Tente novamente");
        }
    }

    private void preencherComboBoxNaoFavoritos() {
        addCombo.removeAllItems();
        //Esse método ele remove do combo o que tinha antes, e vai adicionar novamente.
        //Colocamos esse método para salvar tempo e para não repetir itens quando fosse dar um
        //atualizar na tela.
        idsGeneroNaoFavorito = new ArrayList();
        
        try {
            List<Genero> generos = DAO.ListaGenerosDAO.obterGenerosNaoFavoritos();

            for (Genero f : generos) {
                addCombo.addItem(f.getTipo());
                idsGeneroNaoFavorito.add(f.getIdGenero());

            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Tente novamente");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbGeneroFavorito = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        deleteCombo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        addCombo = new javax.swing.JComboBox<>();
        addBottom = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbGeneroFavorito.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tbGeneroFavorito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Gênero", "Data de Inserção"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbGeneroFavorito.setName(""); // NOI18N
        jScrollPane1.setViewportView(tbGeneroFavorito);

        jButton2.setText(" ↩");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Deletar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        addBottom.setText("Add");
        addBottom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBottomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addCombo, 0, 81, Short.MAX_VALUE)
                    .addComponent(deleteCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBottom))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        TelaDashboard td = new TelaDashboard();
        td.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int index = deleteCombo.getSelectedIndex();
        int idParaDeletar = idsGenerosFavoritos.get(index);
        ListaGenerosDAO.remover(idParaDeletar);
        JOptionPane.showMessageDialog(null, "Registro deletado com sucesso");
        preencherTabela();
        preencherComboBoxDeFavoritos();
        preencherComboBoxNaoFavoritos();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addBottomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBottomActionPerformed
        
        int index = addCombo.getSelectedIndex();
        int idParaAdicionar = idsGeneroNaoFavorito.get(index);
        ListaGenerosDAO.adicionar(idParaAdicionar);
        JOptionPane.showMessageDialog(null, "Registro adicionado com sucesso");
        preencherTabela();
        preencherComboBoxDeFavoritos();
        preencherComboBoxNaoFavoritos();
    }//GEN-LAST:event_addBottomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGeneroFav.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGeneroFav.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGeneroFav.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGeneroFav.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGeneroFav().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBottom;
    private javax.swing.JComboBox<String> addCombo;
    private javax.swing.JComboBox<String> deleteCombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbGeneroFavorito;
    // End of variables declaration//GEN-END:variables
}
